// vue-host/src/App.vue
<script setup>
import LoginWrapper from './components/LoginWrapper.vue'
import SignupWrapper from './components/SignupWrapper.vue'
</script>

<template>
  <div
    style="
      background-color: #0b1020;
      min-height: 100vh;
      color: white;
      padding: 20px;
    "
  >
    <h1>Vue Host Working</h1>

    <LoginWrapper />

    <br /><br />

    <SignupWrapper />
  </div>
</template>

// react-login/src/App.jsx
import Login from './Login'

function App() {
  return (
    <div style={{ padding: '40px', background: '#0b1020', minHeight: '100vh' }}>
      <h1 style={{ color: 'white', textAlign: 'center', marginBottom: '30px' }}>Standalone Login Preview</h1>
      <Login />
    </div>
  )
}

export default App
